# Подбор параметров для PSD

## Импорты

In [1]:
from itertools import product

import pandas as pd
from tqdm import tqdm

from src.signal_processing.feature_engineering import calc_psd_at_step_offset
from src.signal_processing.metrics import eval_metrics

## Загрузка данных

In [2]:
signal_df = pd.read_parquet("../data/Run200_Wave_0_1_base_features.parquet")

## Подбор параметров

In [3]:
offsets = range(6)
gates = range(5, 11)
tasks = list(product(offsets, gates))
metric_cols = ['fom', 'silhouette_score', 'calinski_harabasz_score']
result = []

In [4]:
def eval_for_offset_gate(df, offset_ticks, short_gate):
    arr = calc_psd_at_step_offset(df, offset_ticks=offset_ticks, short_gate=short_gate)['psd'].to_numpy()
    return {k: v for k, v in eval_metrics(arr).items() if k in metric_cols}

In [5]:
for offset, gate in tqdm(tasks):
    acc = {"offset": offset, "gate": gate}
    metrics = eval_for_offset_gate(signal_df, offset_ticks=offset, short_gate=gate)
    acc['fom'] = metrics['fom']
    acc['silhouette_score'] = metrics['silhouette_score']
    acc['calinski_harabasz_score'] = metrics['calinski_harabasz_score']
    result.append(acc)

100%|██████████| 36/36 [10:03<00:00, 16.75s/it]

In [7]:
psd_df = pd.DataFrame(result)
psd_df.head()

   offset  gate       fom  silhouette_score  calinski_harabasz_score
0       0     5  1.147567          0.787785            171279.460695
1       0     6  1.112106          0.774987            153637.749594
2       0     7  1.065691          0.766538            144641.549065
3       0     8  1.024288          0.755772            134096.296664
4       0     9  0.990492          0.754857            133278.593347

In [8]:
psd_df

    offset  gate       fom  silhouette_score  calinski_harabasz_score
0        0     5  1.147567          0.787785            171279.460695
1        0     6  1.112106          0.774987            153637.749594
2        0     7  1.065691          0.766538            144641.549065
3        0     8  1.024288          0.755772            134096.296664
4        0     9  0.990492          0.754857            133278.593347
5        0    10  0.964540          0.741381            121321.451459
6        1     5  1.082490          0.772776            154303.836963
7        1     6  1.035528          0.753806            134228.162777
8        1     7  0.996026          0.753982            134231.488817
9        1     8  0.963995          0.745674            126108.119969
10       1     9  0.938129          0.733339            116196.983982
11       1    10  0.921149          0.722404            108098.158489
12       2     5  0.981177          0.746477            128567.703758
13       2     6  0.949614          0.739555            121475.032332
14       2     7  0.917804          0.728309            112246.869492
15       2     8  0.894652          0.712594            102504.520179
16       2     9  0.881544          0.715758            101353.762257
17       2    10  0.877621          0.715207            100749.916193
18       3     5  0.888135          0.717719            103976.239632
19       3     6  0.861443          0.711110             98160.182871
20       3     7  0.831108          0.701453             90519.654739
21       3     8  0.823540          0.696065             88395.644465
22       3     9  0.826306          0.694597             87561.368515
23       3    10  0.826614          0.693995             85447.291585
24       4     5  0.793406          0.689531             81014.309859
25       4     6  0.762469          0.472733             26236.571209
26       4     7  0.730644          0.318065             11731.196623
27       4     8  0.744068          0.453784             23272.567027
28       4     9  0.752661          0.388265             16418.157038
29       4    10  0.762500          0.358638             13541.764336
30       5     5  0.688303          0.662656             66732.549559
31       5     6  0.661248          0.648611             61436.972991
32       5     7  0.639597          0.637858             58795.433167
33       5     8  0.652177          0.338685             12730.542822
34       5     9  0.667254          0.635166             56487.180117
35       5    10  0.672910          0.640155             58080.091988

Самые лучшие значения offset_ticks=0, short_gate=5. 

В такой конфигурации при переборе параметров получены следующие метрики:
- Figure of Merit = 1.147567
- Silhouette Score = 0.787785
- Calinski-Harabasz Score = 171279.46

Calinski-Harabasz Score оказался слишком чувствительным к таким данным, поэтому будем ориентироваться на FOM и Silhouette.